package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Budynek generated by hbm2java
 */
@Entity
@Table(name = "BUDYNEK", schema = "ADMIN")
public class Budynek implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4061352272679673004L;
	private BigDecimal idBud;
	private Ulica ulica;
	private String nrBud;
	private BigDecimal powBud;
	private Character czyWinda;
	private BigDecimal liczbaPieter;

	public Budynek() {
	}

	public Budynek(BigDecimal idBud, Ulica ulica) {
		this.idBud = idBud;
		this.ulica = ulica;
	}

	public Budynek(BigDecimal idBud, Ulica ulica, String nrBud, BigDecimal powBud, Character czyWinda,
			BigDecimal liczbaPieter) {
		this.idBud = idBud;
		this.ulica = ulica;
		this.nrBud = nrBud;
		this.powBud = powBud;
		this.czyWinda = czyWinda;
		this.liczbaPieter = liczbaPieter;
	}

	@Id

	@Column(name = "ID_BUD", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdBud() {
		return this.idBud;
	}

	public void setIdBud(BigDecimal idBud) {
		this.idBud = idBud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UL", nullable = false)
	public Ulica getUlica() {
		return this.ulica;
	}

	public void setUlica(Ulica ulica) {
		this.ulica = ulica;
	}

	@Column(name = "NR_BUD", length = 1020)
	public String getNrBud() {
		return this.nrBud;
	}

	public void setNrBud(String nrBud) {
		this.nrBud = nrBud;
	}

	@Column(name = "POW_BUD", precision = 22, scale = 0)
	public BigDecimal getPowBud() {
		return this.powBud;
	}

	public void setPowBud(BigDecimal powBud) {
		this.powBud = powBud;
	}

	@Column(name = "CZY_WINDA", length = 1)
	public Character getCzyWinda() {
		return this.czyWinda;
	}

	public void setCzyWinda(Character czyWinda) {
		this.czyWinda = czyWinda;
	}

	@Column(name = "LICZBA_PIETER", precision = 22, scale = 0)
	public BigDecimal getLiczbaPieter() {
		return this.liczbaPieter;
	}

	public void setLiczbaPieter(BigDecimal liczbaPieter) {
		this.liczbaPieter = liczbaPieter;
	}

}
