package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Budynek generated by hbm2java
 */
@Entity
@Table(name = "BUDYNEK", schema = "ADMIN")
public class Budynek implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4061352272679673004L;
	private Integer idBud;
	private Integer idUlica;
	private Ulica ulica;
	private String nrBud;
	private BigDecimal powBud;
	private Boolean czyWinda;
	private BigDecimal liczbaPieter;

	public Budynek() {
	}

	public Budynek(Integer idBud, Ulica ulica) {
		this.idBud = idBud;
		this.ulica = ulica;
	}

	public Budynek(Integer idBud, Ulica ulica, String nrBud, BigDecimal powBud, Boolean czyWinda,
			BigDecimal liczbaPieter) {
		this.idBud = idBud;
		this.ulica = ulica;
		this.nrBud = nrBud;
		this.powBud = powBud;
		this.czyWinda = czyWinda;
		this.liczbaPieter = liczbaPieter;
	}

	@Id
	@GeneratedValue(generator = "SEQ_BUDYNEK", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEQ_BUDYNEK", sequenceName = "ADMIN.SEQ_BUDYNEK", allocationSize=1)
	@Column(name = "ID_BUD", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdBud() {
		return this.idBud;
	}

	public void setIdBud(Integer idBud) {
		this.idBud = idBud;
	}
	
	@Column(name = "ID_UL", insertable = false, updatable = false)
	public Integer getIdUlica() {
		return idUlica;
	}
	
	public void setIdUlica(Integer idUlica) {
		this.idUlica = idUlica;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UL", nullable = false)
	public Ulica getUlica() {
		return this.ulica;
	}

	public void setUlica(Ulica ulica) {
		this.ulica = ulica;
	}

	@Column(name = "NR_BUD", length = 1020)
	public String getNrBud() {
		return this.nrBud;
	}

	public void setNrBud(String nrBud) {
		this.nrBud = nrBud;
	}

	@Column(name = "POW_BUD", precision = 22, scale = 0)
	public BigDecimal getPowBud() {
		return this.powBud;
	}

	public void setPowBud(BigDecimal powBud) {
		this.powBud = powBud;
	}

	@Column(name = "CZY_WINDA", length = 1)
	public Boolean getCzyWinda() {
		return this.czyWinda;
	}

	public void setCzyWinda(Boolean czyWinda) {
		this.czyWinda = czyWinda;
	}

	@Column(name = "LICZBA_PIETER", precision = 22, scale = 0)
	public BigDecimal getLiczbaPieter() {
		return this.liczbaPieter;
	}

	public void setLiczbaPieter(BigDecimal liczbaPieter) {
		this.liczbaPieter = liczbaPieter;
	}
}
