package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cennik generated by hbm2java
 */
@Entity
@Table(name = "CENNIK", schema = "ADMIN")
public class Cennik implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4780921836556071887L;
	private BigDecimal idCennik;
	private BigDecimal idLokal;
	private Date dtCenOd;
	private Date dtCenDo;
	private Double cena;

	public Cennik() {
	}

	public Cennik(BigDecimal idCennik, BigDecimal idLokal) {
		this.idCennik = idCennik;
		this.idLokal = idLokal;
	}

	public Cennik(BigDecimal idCennik, BigDecimal idLokal, Date dtCenOd, Date dtCenDo, Double cena) {
		this.idCennik = idCennik;
		this.idLokal = idLokal;
		this.dtCenOd = dtCenOd;
		this.dtCenDo = dtCenDo;
		this.cena = cena;
	}

	@Id

	@Column(name = "ID_CENNIK", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCennik() {
		return this.idCennik;
	}

	public void setIdCennik(BigDecimal idCennik) {
		this.idCennik = idCennik;
	}

	@Column(name = "ID_LOKAL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdLokal() {
		return this.idLokal;
	}

	public void setIdLokal(BigDecimal idLokal) {
		this.idLokal = idLokal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_CEN_OD", length = 7)
	public Date getDtCenOd() {
		return this.dtCenOd;
	}

	public void setDtCenOd(Date dtCenOd) {
		this.dtCenOd = dtCenOd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_CEN_DO", length = 7)
	public Date getDtCenDo() {
		return this.dtCenDo;
	}

	public void setDtCenDo(Date dtCenDo) {
		this.dtCenDo = dtCenDo;
	}

	@Column(name = "CENA", precision = 2, scale = 0)
	public Double getCena() {
		return this.cena;
	}

	public void setCena(Double cena) {
		this.cena = cena;
	}

}
