package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistPlat generated by hbm2java
 */
@Entity
@Table(name = "HIST_PLAT", schema = "ADMIN")
public class HistPlat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4926260106884681818L;
	private BigDecimal idPlat;
	private Lokator lokator;
	private Double kwotaPlat;
	private Date dtOperacji;
	private Double stanPo;

	public HistPlat() {
	}

	public HistPlat(BigDecimal idPlat, Lokator lokator) {
		this.idPlat = idPlat;
		this.lokator = lokator;
	}

	public HistPlat(BigDecimal idPlat, Lokator lokator, Double kwotaPlat, Date dtOperacji, Double stanPo) {
		this.idPlat = idPlat;
		this.lokator = lokator;
		this.kwotaPlat = kwotaPlat;
		this.dtOperacji = dtOperacji;
		this.stanPo = stanPo;
	}

	@Id
	@GeneratedValue(generator = "SEQ_HIST_PLAT", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEQ_HIST_PLAT", sequenceName = "ADMIN.SEQ_HIST_PLAT", allocationSize=1)
	@Column(name = "ID_PLAT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPlat() {
		return this.idPlat;
	}

	public void setIdPlat(BigDecimal idPlat) {
		this.idPlat = idPlat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_LOKAT", nullable = false)
	public Lokator getLokator() {
		return this.lokator;
	}

	public void setLokator(Lokator lokator) {
		this.lokator = lokator;
	}

	@Column(name = "KWOTA_PLAT", precision = 2, scale = 0)
	public Double getKwotaPlat() {
		return this.kwotaPlat;
	}

	public void setKwotaPlat(Double kwotaPlat) {
		this.kwotaPlat = kwotaPlat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_OPERACJI", length = 7)
	public Date getDtOperacji() {
		return this.dtOperacji;
	}

	public void setDtOperacji(Date dtOperacji) {
		this.dtOperacji = dtOperacji;
	}

	@Column(name = "STAN_PO", precision = 2, scale = 0)
	public Double getStanPo() {
		return this.stanPo;
	}

	public void setStanPo(Double stanPo) {
		this.stanPo = stanPo;
	}

}
