package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Konto generated by hbm2java
 */
@Entity
@Table(name = "KONTO_ROLA_V", schema = "ADMIN")
public class KontoRolaV implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8880965596155970017L;
	private Integer idKont;
	private String login;
	private String passw;
	private String email;
	private String pesel;
	private String telefon;
	private String imie;
	private String nazwisko;
	private Set<Pracownik> pracowniks = new HashSet<Pracownik>(0);
	private Set<Lokator> lokators = new HashSet<Lokator>(0);
	private String aktywny;
	private String rola;
	
	public KontoRolaV() {
	}

	public KontoRolaV(Integer idKont) {
		this.idKont = idKont;
	}

	public KontoRolaV(Integer idKont, String login, String passw, String email, Set<Pracownik> pracowniks,
			Set<Lokator> lokators) {
		this.idKont = idKont;
		this.login = login;
		this.passw = passw;
		this.email = email;
		this.pracowniks = pracowniks;
		this.lokators = lokators;
	}

	@Id
	@Column(name = "ID_KONT", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdKont() {
		return this.idKont;
	}

	public void setIdKont(Integer idKont) {
		this.idKont = idKont;
	}

	@Column(name = "LOGIN", length = 255)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSW", length = 255)
	public String getPassw() {
		return this.passw;
	}

	public void setPassw(String passw) {
		this.passw = passw;
	}

	@Column(name = "EMAIL", length = 255)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "konto")
	public Set<Pracownik> getPracowniks() {
		return this.pracowniks;
	}

	public void setPracowniks(Set<Pracownik> pracowniks) {
		this.pracowniks = pracowniks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "konto")
	public Set<Lokator> getLokators() {
		return this.lokators;
	}

	public void setLokators(Set<Lokator> lokators) {
		this.lokators = lokators;
	}

	@Column(name = "PESEL", length = 15)
	public String getPesel() {
		return pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}
	
	@Column(name = "TELEFON", length = 20)
	public String getTelefon() {
		return telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}
	
	@Column(name = "IMIE", length = 64)
	public String getImie() {
		return imie;
	}

	public void setImie(String imie) {
		this.imie = imie;
	}
	
	@Column(name = "NAZWISKO", length = 64)
	public String getNazwisko() {
		return nazwisko;
	}

	public void setNazwisko(String nazwisko) {
		this.nazwisko = nazwisko;
	}

	@Column(name = "ROLA")
	public String getRola() {
		return rola;
	}

	public void setRola(String rola) {
		this.rola = rola;
	}

	@Column(name = "AKTYWNY", length = 1)
	public String getAktywny() {
		return aktywny;
	}

	public void setAktywny(String aktywny) {
		this.aktywny = aktywny;
	}

	@Transient
	public String getImieNazwisko() {
		return imie + " " + nazwisko;
	}
	
}
