package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lokator generated by hbm2java
 */
@Entity
@Table(name = "LOKATOR", schema = "ADMIN")
public class Lokator implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1435543839289678919L;
	private BigDecimal idLokat;
	private Konto konto;
	private String imieLokat;
	private String nazwLokat;
	private String pesel;
	private String nrTelLok;
	private Set<HistPlat> histPlats = new HashSet<HistPlat>(0);
	private Set<StanKonta> stanKontas = new HashSet<StanKonta>(0);
	private Set<Rozliczenie> rozliczenies = new HashSet<Rozliczenie>(0);
	private Set<Wynajem> wynajems = new HashSet<Wynajem>(0);

	public Lokator() {
	}

	public Lokator(BigDecimal idLokat, Konto konto) {
		this.idLokat = idLokat;
		this.konto = konto;
	}

	public Lokator(BigDecimal idLokat, Konto konto, String imieLokat, String nazwLokat, String pesel, String nrTelLok,
			Set<HistPlat> histPlats, Set<StanKonta> stanKontas, Set<Rozliczenie> rozliczenies, Set<Wynajem> wynajems) {
		this.idLokat = idLokat;
		this.konto = konto;
		this.imieLokat = imieLokat;
		this.nazwLokat = nazwLokat;
		this.pesel = pesel;
		this.nrTelLok = nrTelLok;
		this.histPlats = histPlats;
		this.stanKontas = stanKontas;
		this.rozliczenies = rozliczenies;
		this.wynajems = wynajems;
	}

	@Id

	@Column(name = "ID_LOKAT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdLokat() {
		return this.idLokat;
	}

	public void setIdLokat(BigDecimal idLokat) {
		this.idLokat = idLokat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_KONT", nullable = false)
	public Konto getKonto() {
		return this.konto;
	}

	public void setKonto(Konto konto) {
		this.konto = konto;
	}

	@Column(name = "IMIE_LOKAT", length = 1020)
	public String getImieLokat() {
		return this.imieLokat;
	}

	public void setImieLokat(String imieLokat) {
		this.imieLokat = imieLokat;
	}

	@Column(name = "NAZW_LOKAT", length = 1020)
	public String getNazwLokat() {
		return this.nazwLokat;
	}

	public void setNazwLokat(String nazwLokat) {
		this.nazwLokat = nazwLokat;
	}

	@Column(name = "PESEL", length = 1020)
	public String getPesel() {
		return this.pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}

	@Column(name = "NR_TEL_LOK", length = 64)
	public String getNrTelLok() {
		return this.nrTelLok;
	}

	public void setNrTelLok(String nrTelLok) {
		this.nrTelLok = nrTelLok;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lokator")
	public Set<HistPlat> getHistPlats() {
		return this.histPlats;
	}

	public void setHistPlats(Set<HistPlat> histPlats) {
		this.histPlats = histPlats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lokator")
	public Set<StanKonta> getStanKontas() {
		return this.stanKontas;
	}

	public void setStanKontas(Set<StanKonta> stanKontas) {
		this.stanKontas = stanKontas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lokator")
	public Set<Rozliczenie> getRozliczenies() {
		return this.rozliczenies;
	}

	public void setRozliczenies(Set<Rozliczenie> rozliczenies) {
		this.rozliczenies = rozliczenies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lokator")
	public Set<Wynajem> getWynajems() {
		return this.wynajems;
	}

	public void setWynajems(Set<Wynajem> wynajems) {
		this.wynajems = wynajems;
	}

}
