package com.buildings.model;


import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Okres generated by hbm2java
 */
@Entity
@Table(name = "OKRES", schema = "ADMIN")
public class Okres implements Serializable {

	private static final long serialVersionUID = -9107098609022904692L;
	
	@Id
	@Column(name = "ID_OKR", unique = true, nullable = false, precision = 22, scale = 0)
	private BigDecimal idOkr;
	
	@Column(name = "MIES", precision = 22, scale = 0)
	private BigDecimal mies;
	
	@Column(name = "ROK", precision = 22, scale = 0)
	private BigDecimal rok;

	public Okres() {
	}

	public Okres(BigDecimal idOkr) {
		this.idOkr = idOkr;
	}

	public Okres(BigDecimal idOkr, BigDecimal mies, BigDecimal rok) {
		this.idOkr = idOkr;
		this.mies = mies;
		this.rok = rok;
	}

	public BigDecimal getIdOkr() {
		return this.idOkr;
	}

	public void setIdOkr(BigDecimal idOkr) {
		this.idOkr = idOkr;
	}


	public BigDecimal getMies() {
		return this.mies;
	}

	public void setMies(BigDecimal mies) {
		this.mies = mies;
	}

	public BigDecimal getRok() {
		return this.rok;
	}

	public void setRok(BigDecimal rok) {
		this.rok = rok;
	}


}