package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rozliczenie generated by hbm2java
 */
@Entity
@Table(name = "ROZLICZENIE", schema = "ADMIN")
public class Rozliczenie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 132717687430566977L;
	private BigDecimal idPlat;
	private Integer idLokat;
	private Lokator lokator;
	private Okres okres;
	private Double saldoMies;
	private Double obciazenie;
	private Date data;
	private Date terminPlat;
	
	public Rozliczenie() {
		this.okres = new Okres();
		this.okres.setIdOkr(null);
	}

	public Rozliczenie(BigDecimal idPlat, Lokator lokator, Okres okres) {
		this.idPlat = idPlat;
		this.lokator = lokator;
		this.okres = okres;
	}

	public Rozliczenie(BigDecimal idPlat, Lokator lokator, Okres okres, Double saldoMies, Date data, Date terminPlat) {
		this.idPlat = idPlat;
		this.lokator = lokator;
		this.okres = okres;
		this.saldoMies = saldoMies;
		this.data = data;
		this.terminPlat = terminPlat;
	}

	@Id
	@GeneratedValue(generator = "SEQ_ROZLICZENIE", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEQ_ROZLICZENIE", sequenceName = "ADMIN.SEQ_ROZLICZENIE", allocationSize=1)
	@Column(name = "ID_PLAT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPlat() {
		return this.idPlat;
	}

	public void setIdPlat(BigDecimal idPlat) {
		this.idPlat = idPlat;
	}

	@Column(name = "ID_LOKAT", insertable = false, updatable = false)
	public Integer getIdLokat() {
		return this.idLokat;
	}

	public void setIdLokat(Integer idLokat) {
		this.idLokat = idLokat;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_LOKAT", nullable = false)
	public Lokator getLokator() {
		return this.lokator;
	}

	public void setLokator(Lokator lokator) {
		this.lokator = lokator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_OKR", nullable = false)
	public Okres getOkres() {
		return this.okres;
	}

	public void setOkres(Okres okres) {
		this.okres = okres;
	}

	@Column(name = "SALDO_MIES", precision = 2, scale = 0)
	public Double getSaldoMies() {
		return this.saldoMies;
	}
	
	@Column(name = "OBCIAZENIE", precision = 2, scale = 0)
	public Double getObciazenie() {
		return this.obciazenie;
	}

	public void setSaldoMies(Double saldoMies) {
		this.saldoMies = saldoMies;
	}
	
	public void setObciazenie(Double obciazenie) {
		this.obciazenie = obciazenie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA", length = 7)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TERMIN_PLAT", length = 7)
	public Date getTerminPlat() {
		return this.terminPlat;
	}

	public void setTerminPlat(Date terminPlat) {
		this.terminPlat = terminPlat;
	}

}
