package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StanKonta generated by hbm2java
 */
@Entity
@Table(name = "STAN_KONTA", schema = "ADMIN")
public class StanKonta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8438753932937052856L;
	private BigDecimal idStan;
	private Lokator lokator;
	private Double stan;

	public StanKonta() {
	}

	public StanKonta(BigDecimal idStan, Lokator lokator) {
		this.idStan = idStan;
		this.lokator = lokator;
	}

	public StanKonta(BigDecimal idStan, Lokator lokator, Double stan) {
		this.idStan = idStan;
		this.lokator = lokator;
		this.stan = stan;
	}

	@Id

	@Column(name = "ID_STAN", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdStan() {
		return this.idStan;
	}

	public void setIdStan(BigDecimal idStan) {
		this.idStan = idStan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_LOKAT", nullable = false)
	public Lokator getLokator() {
		return this.lokator;
	}

	public void setLokator(Lokator lokator) {
		this.lokator = lokator;
	}

	@Column(name = "STAN", precision = 2, scale = 0)
	public Double getStan() {
		return this.stan;
	}

	public void setStan(Double stan) {
		this.stan = stan;
	}

}
