package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Ulica generated by hbm2java
 */
@Entity
@Table(name = "ULICA", schema = "ADMIN")
public class Ulica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6054158643347272286L;
	private Integer idUl;
	private Miasto miasto;
	private String nazwaUl;
	private Set<Firma> firmas = new HashSet<Firma>(0);
	private Set<Budynek> budyneks = new HashSet<Budynek>(0);

	public Ulica() {
	}

	public Ulica(Integer idUl, Miasto miasto) {
		this.idUl = idUl;
		this.miasto = miasto;
	}

	public Ulica(Integer idUl, Miasto miasto, String nazwaUl, Set<Firma> firmas, Set<Budynek> budyneks) {
		this.idUl = idUl;
		this.miasto = miasto;
		this.nazwaUl = nazwaUl;
		this.firmas = firmas;
		this.budyneks = budyneks;
	}

	@Id
	@GeneratedValue(generator = "SEQ_ULICA", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEQ_ULICA", sequenceName = "ADMIN.SEQ_ULICA", allocationSize=1)
	@Column(name = "ID_UL", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdUl() {
		return this.idUl;
	}

	public void setIdUl(Integer idUl) {
		this.idUl = idUl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MIAST", nullable = false)
	public Miasto getMiasto() {
		return this.miasto;
	}

	public void setMiasto(Miasto miasto) {
		this.miasto = miasto;
	}

	@Column(name = "NAZWA_UL", length = 1020)
	public String getNazwaUl() {
		return this.nazwaUl;
	}

	public void setNazwaUl(String nazwaUl) {
		this.nazwaUl = nazwaUl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ulica")
	public Set<Firma> getFirmas() {
		return this.firmas;
	}

	public void setFirmas(Set<Firma> firmas) {
		this.firmas = firmas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ulica")
	public Set<Budynek> getBudyneks() {
		return this.budyneks;
	}

	public void setBudyneks(Set<Budynek> budyneks) {
		this.budyneks = budyneks;
	}

}
