package com.buildings.model;
//Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
* Ulica generated by hbm2java
*/
@Entity
@Table(name = "USTERKA", schema = "ADMIN")
public class Usterka implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1744600131881263866L;
	
	private Integer idUsterka;
	private Boolean lokalna;
	private String opis;
	private String status;
	private String priorUster;

	public Usterka() {
	}

	public Usterka(Integer idUst, String opis) {
		this.idUsterka = idUst;
		this.opis = opis;
	}

	@Id
	@GeneratedValue(generator = "SEQ_USTERKA", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEQ_USTERKA", sequenceName = "ADMIN.SEQ_USTERKA", allocationSize=1)
	@Column(name = "ID_USTER", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdUsterka() {
		return this.idUsterka;
	}

	public void setIdUsterka(Integer idUsterka) {
		this.idUsterka = idUsterka;
	}
	
	@Column(name = "IS_LOKALNA")
	public Boolean getLokalna() {
		return this.lokalna;
	}
	
	public void setLokalna(Boolean lokalna) {
		this.lokalna = lokalna;
	}
	
	@Column(name = "OPIS", length = 1020)
	public String getOpis() {
		return opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}
	
	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "PRIOR_USTER", length = 1)
	public String getPriorUster() {
		return priorUster;
	}

	public void setPriorUster(String priorUster) {
		this.priorUster = priorUster;
	}

}
