package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wynajem generated by hbm2java
 */
@Entity
@Table(name = "WYNAJEM", schema = "ADMIN")
public class Wynajem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1000644206029040331L;
	private Integer idWynaj;
	private Integer idLokator;
	private Lokator lokator;
	private Integer idLokal;
	private String nrUmowy;
	private Double cenaWynaj;
	private Date dtUmowyOd;
	private Date dtUmowyDo;
	private Set<Zgloszenie> zgloszenies = new HashSet<Zgloszenie>(0);

	public Wynajem() {
	}

	public Wynajem(Integer idWynaj, Lokator lokator, Integer idLokal) {
		this.idWynaj = idWynaj;
		this.lokator = lokator;
		this.idLokal = idLokal;
	}

	public Wynajem(Integer idWynaj, Lokator lokator, Integer idLokal, String nrUmowy, Double cenaWynaj,
			Date dtUmowyOd, Date dtUmowyDo, Set<Zgloszenie> zgloszenies) {
		this.idWynaj = idWynaj;
		this.lokator = lokator;
		this.idLokal = idLokal;
		this.nrUmowy = nrUmowy;
		this.cenaWynaj = cenaWynaj;
		this.dtUmowyOd = dtUmowyOd;
		this.dtUmowyDo = dtUmowyDo;
		this.zgloszenies = zgloszenies;
	}

	@Id
	@GeneratedValue(generator = "SEQ_WYNAJEM", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "SEQ_WYNAJEM", sequenceName = "ADMIN.SEQ_WYNAJEM", allocationSize=1)
	@Column(name = "ID_WYNAJ", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdWynaj() {
		return this.idWynaj;
	}

	public void setIdWynaj(Integer idWynaj) {
		this.idWynaj = idWynaj;
	}

	@Column(name = "ID_LOKAT", insertable = false, updatable = false)
	public Integer getIdLokator() {
		return this.idLokator;
	}
	
	public void setIdLokator(Integer idLokator) {
		this.idLokator = idLokator;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_LOKAT", nullable = false)
	public Lokator getLokator() {
		return this.lokator;
	}

	public void setLokator(Lokator lokator) {
		this.lokator = lokator;
	}

	@Column(name = "ID_LOKAL", nullable = false, precision = 22, scale = 0)
	public Integer getIdLokal() {
		return this.idLokal;
	}

	public void setIdLokal(Integer idLokal) {
		this.idLokal = idLokal;
	}

	@Column(name = "NR_UMOWY", length = 256)
	public String getNrUmowy() {
		return this.nrUmowy;
	}

	public void setNrUmowy(String nrUmowy) {
		this.nrUmowy = nrUmowy;
	}

	@Column(name = "CENA_WYNAJ", precision = 2, scale = 0)
	public Double getCenaWynaj() {
		return this.cenaWynaj;
	}

	public void setCenaWynaj(Double cenaWynaj) {
		this.cenaWynaj = cenaWynaj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_UMOWY_OD", length = 7)
	public Date getDtUmowyOd() {
		return this.dtUmowyOd;
	}

	public void setDtUmowyOd(Date dtUmowyOd) {
		this.dtUmowyOd = dtUmowyOd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_UMOWY_DO", length = 7)
	public Date getDtUmowyDo() {
		return this.dtUmowyDo;
	}

	public void setDtUmowyDo(Date dtUmowyDo) {
		this.dtUmowyDo = dtUmowyDo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wynajem")
	public Set<Zgloszenie> getZgloszenies() {
		return this.zgloszenies;
	}

	public void setZgloszenies(Set<Zgloszenie> zgloszenies) {
		this.zgloszenies = zgloszenies;
	}

}
