package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zadanie generated by hbm2java
 */
@Entity
@Table(name = "ZADANIE", schema = "ADMIN")
public class Zadanie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6282305712629536226L;
	private BigDecimal idZad;
	private Firma firma;
	private Pracownik pracownik;
	private BigDecimal idUster;
	private Character obciazenie;
	private Date dtZgloszenia;
	private Date dtPlan;
	private Date dtZakon;
	private BigDecimal statusZad;

	public Zadanie() {
	}

	public Zadanie(BigDecimal idZad, Firma firma, Pracownik pracownik, BigDecimal idUster) {
		this.idZad = idZad;
		this.firma = firma;
		this.pracownik = pracownik;
		this.idUster = idUster;
	}

	public Zadanie(BigDecimal idZad, Firma firma, Pracownik pracownik, BigDecimal idUster, Character obciazenie,
			Date dtZgloszenia, Date dtPlan, Date dtZakon, BigDecimal statusZad) {
		this.idZad = idZad;
		this.firma = firma;
		this.pracownik = pracownik;
		this.idUster = idUster;
		this.obciazenie = obciazenie;
		this.dtZgloszenia = dtZgloszenia;
		this.dtPlan = dtPlan;
		this.dtZakon = dtZakon;
		this.statusZad = statusZad;
	}

	@Id

	@Column(name = "ID_ZAD", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdZad() {
		return this.idZad;
	}

	public void setIdZad(BigDecimal idZad) {
		this.idZad = idZad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FIRMY", nullable = false)
	public Firma getFirma() {
		return this.firma;
	}

	public void setFirma(Firma firma) {
		this.firma = firma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRAC", nullable = false)
	public Pracownik getPracownik() {
		return this.pracownik;
	}

	public void setPracownik(Pracownik pracownik) {
		this.pracownik = pracownik;
	}

	@Column(name = "ID_USTER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUster() {
		return this.idUster;
	}

	public void setIdUster(BigDecimal idUster) {
		this.idUster = idUster;
	}

	@Column(name = "OBCIAZENIE", length = 1)
	public Character getObciazenie() {
		return this.obciazenie;
	}

	public void setObciazenie(Character obciazenie) {
		this.obciazenie = obciazenie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ZGLOSZENIA", length = 7)
	public Date getDtZgloszenia() {
		return this.dtZgloszenia;
	}

	public void setDtZgloszenia(Date dtZgloszenia) {
		this.dtZgloszenia = dtZgloszenia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_PLAN", length = 7)
	public Date getDtPlan() {
		return this.dtPlan;
	}

	public void setDtPlan(Date dtPlan) {
		this.dtPlan = dtPlan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_ZAKON", length = 7)
	public Date getDtZakon() {
		return this.dtZakon;
	}

	public void setDtZakon(Date dtZakon) {
		this.dtZakon = dtZakon;
	}

	@Column(name = "STATUS_ZAD", precision = 22, scale = 0)
	public BigDecimal getStatusZad() {
		return this.statusZad;
	}

	public void setStatusZad(BigDecimal statusZad) {
		this.statusZad = statusZad;
	}

}
