package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zgloszenie generated by hbm2java
 */
@Entity
@Table(name = "ZGLOSZENIE", schema = "ADMIN")
public class Zgloszenie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 692692172327843667L;
	private ZgloszenieId id;
	private Wynajem wynajem;

	public Zgloszenie() {
	}

	public Zgloszenie(ZgloszenieId id, Wynajem wynajem) {
		this.id = id;
		this.wynajem = wynajem;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idWynaj", column = @Column(name = "ID_WYNAJ", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idUsterka", column = @Column(name = "ID_USTERKA", nullable = false, precision = 22, scale = 0)) })
	public ZgloszenieId getId() {
		return this.id;
	}

	public void setId(ZgloszenieId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_WYNAJ", nullable = false, insertable = false, updatable = false)
	public Wynajem getWynajem() {
		return this.wynajem;
	}

	public void setWynajem(Wynajem wynajem) {
		this.wynajem = wynajem;
	}

}
