package com.buildings.model;
// Generated Jun 2, 2017 5:05:24 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ZgloszenieId generated by hbm2java
 */
@Embeddable
public class ZgloszenieId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4811955625784145384L;
	private BigDecimal idWynaj;
	private BigDecimal idUsterka;

	public ZgloszenieId() {
	}

	public ZgloszenieId(BigDecimal idWynaj, BigDecimal idUsterka) {
		this.idWynaj = idWynaj;
		this.idUsterka = idUsterka;
	}

	@Column(name = "ID_WYNAJ", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdWynaj() {
		return this.idWynaj;
	}

	public void setIdWynaj(BigDecimal idWynaj) {
		this.idWynaj = idWynaj;
	}

	@Column(name = "ID_USTERKA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUsterka() {
		return this.idUsterka;
	}

	public void setIdUsterka(BigDecimal idUsterka) {
		this.idUsterka = idUsterka;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZgloszenieId))
			return false;
		ZgloszenieId castOther = (ZgloszenieId) other;

		return ((this.getIdWynaj() == castOther.getIdWynaj()) || (this.getIdWynaj() != null
				&& castOther.getIdWynaj() != null && this.getIdWynaj().equals(castOther.getIdWynaj())))
				&& ((this.getIdUsterka() == castOther.getIdUsterka()) || (this.getIdUsterka() != null
						&& castOther.getIdUsterka() != null && this.getIdUsterka().equals(castOther.getIdUsterka())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdWynaj() == null ? 0 : this.getIdWynaj().hashCode());
		result = 37 * result + (getIdUsterka() == null ? 0 : this.getIdUsterka().hashCode());
		return result;
	}

}
